### PR TITLE
contributors page added

### PR DESCRIPTION
**Pull request by vedikaag99**
https://user-images.githubusercontent.com/67699840/114299203-b594b500-9ad7-11eb-94ff-f79d10f0013b.mov

### CODE REVIEW

**Comment by LordShenron** [comment]
Hello vedikaag99, I will be reviewing this PR because Arun broke his laptop and is currently waiting for it to be fixed.

**Review by LordShenron — CHANGES_REQUESTED** [review]
Okay.. It looks fine to me but most of our maintainers don't use LinkedIn so I feel it's better to add Telegram or discord there instead of LinkedIn. 

Second.. we have a devices.json with maintainers names on it we can create a contributors.json if it needed so instead of hardcoding everyperson here can we just fetch the details from that json files (PS: they work as an API)

**Comment by vedikaag99** [comment]
> Okay.. It looks fine to me but most of our maintainers don't use LinkedIn so I feel it's better to add Telegram or discord there instead of LinkedIn.
> 
> Second.. we have a devices.json with maintainers names on it we can create a contributors.json if it needed so instead of hardcoding everyperson here can we just fetch the details from that json files (PS: they work as an API)

got it! Can you please give me the link to the devices.json file so that I can use it for reference?

**Comment by LordShenron** [comment]
> > Okay.. It looks fine to me but most of our maintainers don't use LinkedIn so I feel it's better to add Telegram or discord there instead of LinkedIn.
> > Second.. we have a devices.json with maintainers names on it we can create a contributors.json if it needed so instead of hardcoding everyperson here can we just fetch the details from that json files (PS: they work as an API)
> 
> got it! Can you please give me the link to the devices.json file so that I can use it for reference?

here ya go..
https://github.com/ProjectSakura/OTA/blob/11/devices.json

if you need a specific structure  then we can add a new json to fulfill that.

**Review by LordShenron — COMMENTED** [review]
Instead of creating a data.js into the website itself don;t u feel its better to use it from OTA?

**Comment by vedikaag99** [comment]
> Instead of creating a data.js into the website itself don;t u feel its better to use it from OTA?

Can you guide me on how to do so? @LordShenron 
Will I have to open a PR in the OTA repository adding my data.js file there? Also, I have no idea on how to use file from another repository and import it in this repo

**Comment by LordShenron** [comment]
> > Instead of creating a data.js into the website itself don;t u feel its better to use it from OTA?
> 
> Can you guide me on how to do so? @LordShenron
> Will I have to open a PR in the OTA repository adding my data.js file there? Also, I have no idea on how to use file from another repository and import it in this repo

see this commit: https://github.com/ProjectSakura/download/commit/d88d8d5580e19f45e5274be02a347397992c2455

**Comment by ArunTeltia** [comment]
Lets add this for now I will start working on the json file today @LordShenron  merge bruh

**Comment by ArunTeltia** [comment]
Also @vedikaag99 sorry if i am asking a lot but can you create a pr for github action that will add the tags on its own

**Comment by vedikaag99** [comment]
> Also @vedikaag99 sorry if i am asking a lot but can you create a pr for github action that will add the tags on its own

Sure, no issues!

**Review by ArunTeltia — CHANGES_REQUESTED** [review]
I have one issue @vedikaag99  we are using bootstrap in it can we remove it I dont like bootstrap and it is absolute redundent we can work with material ui and that is very light weight

**Comment by LordShenron** [comment]
> I have one issue @vedikaag99 we are using bootstrap in it can we remove it I dont like bootstrap and it is absolute redundent we can work with material ui and that is very light weight

Just make it again from scratch.

**Comment by ArunTeltia** [comment]
Material ui to kar rahe hai apne use, I dont care what you say 🤓😏

**Comment by LordShenron** [comment]
> Material ui to kar rahe hai apne use, I dont care what you say nerd_facesmirk

idk man.. i just want this shit to go live before I die

**Comment by ArunTeltia** [comment]
😂😂

**Pull request merged**
